[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["ClimaBot <ci-bot@climacell.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aoc_2020"
path = "src/lib.rs"

[dependencies]
